=== firstsheep1984/Web-Service/ShoppingProject/Customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/Customer/" targetNamespace="http://www.example.org/Customer/">
    <element name="customer" type="tns:Customer"></element>


    <complexType name="Customer">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="family" type="string"></element>
    		<element name="birthday" type="date"></element>
    		<element name="email" type="string"></element>
    		<element name="phone" type="string"></element>
    		<element name="gender" type="tns:genderType"></element>
    		<element name="payment" type="tns:paymentType"></element>
    		<element name="address" type="tns:Address"></element>
    	</sequence>
    </complexType>


    <simpleType name="genderType">
    	<restriction base="string">
    		<enumeration value="M"></enumeration>
    		<enumeration value="F"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="paymentType">
    	<sequence>
    		<element name="TypeOfCard" type="tns:typeOfCardType"></element>
    		<element name="CardNumber" type="string"></element>
    	</sequence>
    </complexType>

    <simpleType name="typeOfCardType">
    	<restriction base="string">
    		<enumeration value="visa"></enumeration>
    		<enumeration value="master"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="Address">
    	<sequence>
    		<element name="numer" type="int"></element>
    		<element name="streetAddress" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="country" type="string"></element>
    		<element name="zipcode" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== firstsheep1984/Web-Service/ShoppingProject/Customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:customer xmlns:tns="http://www.example.org/Customer/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Customer/ Customer.xsd ">
  <name>Lan</name>
  <family>Lee</family>
  <birthday>1988-02-05</birthday>
  <email>lan@gmail.com</email>
  <phone>5146669999</phone>
  <gender>M</gender>
  <payment>
    <TypeOfCard>visa</TypeOfCard>
    <CardNumber>6666777788889999</CardNumber>
  </payment>
  <address>
    <numer>11</numer>
    <streetAddress>ewer</streetAddress>
    <city>Montreal</city>
    <state>QC</state>
    <country>CA</country>
    <zipcode>H6T3R2</zipcode>
  </address>
</tns:customer>
